### ISSUE TITLE
Implement `Random visual novel` link

### ISSUE THREAD

**Issue by NightOfNights** [vndbre/vndbre#158]

**Comment by NightOfNights** [comment]
@prekel Could you implement proxy for [dbstats](https://vndb.org/d11#4) request?

**Comment by prekel** [comment]
> @prekel Could you implement proxy for [dbstats](https://vndb.org/d11#4) request?

It is already implemented, you can send "dbstats" as command like this: 
![Screenshot_20220515-223600.jpg](https://user-images.githubusercontent.com/19646569/168481150-ca081afb-5a53-400c-966e-09ba0433f40a.jpg)
