### ISSUE TITLE
Implement links to external resources in novel page

### ISSUE THREAD

**Issue by prekel** [vndbre/vndbre#90]
https://vndb.org/d11#5.1
>```
>Contains the following members:
>"wikipedia", string, name of the related article on the English Wikipedia (deprecated, use wikidata instead).
>"[encubed](http://novelnews.net/)", string, the URL-encoded tag used on encubed (deprecated).
>"renai", string, the name part of the url on [renai.us](http://renai.us/).
>"wikidata", string, Wikidata identifier.
>All members can be null when no links are available or known to us.
>```

![image](https://user-images.githubusercontent.com/19646569/153136928-463cf1b9-d3a6-4b88-a89c-fe3a8fe4667e.png)

And a link to vndb.org can be added

**Comment by Moltenship** [comment]
Will be fixed in next milestone

**Comment by NightOfNights** [comment]
Has been fixed by #135
